CREATE TABLE programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE applicants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE applications (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  applicant_id BIGINT NOT NULL REFERENCES applicants(id),
  program_id BIGINT NOT NULL REFERENCES programs(id),
  status TEXT NOT NULL CHECK (status IN ('submitted', 'approved', 'rejected')),
  submitted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMP
);

CREATE UNIQUE INDEX one_application_per_program
ON applications(applicant_id, program_id);
